---
- hosts: all
  tasks:
    - name: block task
      block:
        - debug:
            msg: 'start'
        - ping:
        - debug:
            msg: 'end'

      when: inventory_hostname == 'localhost'